# Generated by Django 4.2.11 on 2024-04-23 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ekartapp', '0002_product_stock'),
        ('payments', '0002_product_rename_price_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ekartapp.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
