# Generated by Django 4.2.11 on 2024-05-02 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ekartapp', '0002_product_stock'),
        ('payments', '0003_alter_order_product_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ekartapp.product')),
            ],
        ),
    ]
