# Generated by Django 4.2.11 on 2024-03-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ekartapp', '0003_rename_descsription_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
