# Generated by Django 4.2.11 on 2024-04-01 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ekartapp', '0004_product_paid_product_razorpay_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='razorpay_payment_id',
        ),
    ]
