# Generated by Django 4.2.11 on 2024-04-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ekartapp', '0005_remove_product_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packet_size',
            field=models.CharField(choices=[('100g', '100 grams'), ('200g', '200 grams'), ('500g', '500 grams'), ('1kg', '1 kilogram')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
