# Generated by Django 4.2.11 on 2024-04-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ekartapp', '0005_remove_product_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='grams',
            field=models.IntegerField(choices=[(20, '20g'), (60, '60g'), (130, '130g'), (150, '150g'), (300, '300g'), (400, '400g')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='packet',
            field=models.CharField(choices=[('Pillow Pouch', 'Pillow Pouch'), ('Standup Pouch', 'Standup Pouch'), ('Pouch', 'Pouch'), ('Bottle', 'Bottle'), ('Box', 'Box')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
