# Generated by Django 4.2.11 on 2024-04-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ekartapp', '0006_product_packet_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='packet_size',
        ),
    ]
