# Generated by Django 4.2.11 on 2024-04-12 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ekartapp', '0010_remove_product_price_remove_product_stock_packetsize'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ekartapp.packetsize'),
        ),
    ]
